apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: "{{.DOCKER_REGISTRY}}/qwerzy:{{.VERSION}}"
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/qwerzy:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/qwerzy:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: qwerzy
        chartPath: charts/qwerzy
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/qwerzy'
          image.tag: '{{.DIGEST_HEX}}'
